//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocukYazini.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class adtable
    {
        public long id { get; set; }
        public Nullable<System.DateTime> reklamstart { get; set; }
        public Nullable<System.DateTime> reklamend { get; set; }
        public string reklamurl { get; set; }
        public string reklamphotourl { get; set; }
        public string reklamfooter { get; set; }
        public string reklamside { get; set; }
    }
}
