//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocukYazini.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class contacttable
    {
        public long id { get; set; }
        public string contacttitle { get; set; }
        public string contactcontent { get; set; }
        public string email { get; set; }
        public string whowrote { get; set; }
        public Nullable<long> userid { get; set; }
        public Nullable<int> isaktif { get; set; }
        public Nullable<System.DateTime> contacttime { get; set; }
    
        public virtual usertable usertable { get; set; }
    }
}
