//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocukYazini.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cocukyaziniEntities : DbContext
    {
        public cocukyaziniEntities()
            : base("name=cocukyaziniEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categorytable> categorytables { get; set; }
        public virtual DbSet<comenttable> comenttables { get; set; }
        public virtual DbSet<contacttable> contacttables { get; set; }
        public virtual DbSet<monthtable> monthtables { get; set; }
        public virtual DbSet<posttable> posttables { get; set; }
        public virtual DbSet<slidertable> slidertables { get; set; }
        public virtual DbSet<sorusturma> sorusturmas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<uploadtable> uploadtables { get; set; }
        public virtual DbSet<usertable> usertables { get; set; }
    }
}
