//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocukYazini.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class posttable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public posttable()
        {
            this.comenttables = new HashSet<comenttable>();
        }
    
        public long id { get; set; }
        public string posttitle { get; set; }
        public string postcontent { get; set; }
        public Nullable<long> categoryid { get; set; }
        public Nullable<long> userid { get; set; }
        public string whowrote { get; set; }
        public string previewphoto { get; set; }
        public string postphoto { get; set; }
        public Nullable<int> isaktif { get; set; }
        public Nullable<System.DateTime> posttime { get; set; }
        public Nullable<long> monthid { get; set; }
        public Nullable<long> sorusturmaid { get; set; }
        public string postspot { get; set; }
        public Nullable<long> postviewcount { get; set; }
        public string postvitrin { get; set; }
    
        public virtual categorytable categorytable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comenttable> comenttables { get; set; }
        public virtual monthtable monthtable { get; set; }
        public virtual sorusturma sorusturma { get; set; }
        public virtual usertable usertable { get; set; }
    }
}
