//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocukYazini.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class videotable
    {
        public long id { get; set; }
        public string videotitle { get; set; }
        public string videodescription { get; set; }
        public string videourl { get; set; }
        public Nullable<System.DateTime> videotime { get; set; }
    }
}
